name: ux_improvements
description: "Improvements to your overall UI/UX through various Widgets."
version: 0.13.5
repository: https://github.com/YukiAttano/package-ux_improvements
issue_tracker: https://github.com/YukiAttano/package-ux_improvements/issues
topics:
  - widget
  - ui
  - ux
  - image
  - flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  responsive_ux: ^1.0.1

  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #

dart:
  records: enabled